// Python ↔ TypeScript metric parity.
//
// The fixture `metric_parity.json` is generated by Python:
//   python frontend/tests/fixtures/dump_metric_parity.py
// It contains a synthetic tile grid and three polygons, and the
// reference `compute_roi_metrics` output Python produces for each
// polygon at K=2000 MC samples.
//
// On the TS side we read the same fixture, rebuild the tile arrays
// into the same shape, run `computeROIMetrics`, and verify the deltas
// against Python are tight. Because the two implementations use
// different PRNG streams (Mulberry32 vs numpy's PCG-64), the percentile
// estimates do NOT agree bit-for-bit; the point estimates and tile
// counts DO agree to machine precision, and the MC percentiles agree
// to within the natural sampling noise (~3% relative).

import { describe, expect, it } from "vitest";

import { computeROIMetrics } from "@/lib/macrodissection/metrics";
import type { Point2D, TileArrays, TileGridMeta } from "@/lib/macrodissection/types";

interface Fixture {
  grid: TileGridMeta;
  thresholds: { purity_min: number; tumor_cells_min: number };
  tiles: {
    purity: number[];
    purity_sd: number[];
    nuclei: number[];
    nuclei_sd: number[];
    tissue_fraction: number[];
  };
  cases: Array<{
    label: string;
    polygon: [number, number][];
    expected: {
      n_tiles: number;
      tiles_with_data: number;
      area_thumbpx2: number;
      area_mm2: number;
      purity_point: number;
      total_nuclei_point: number;
      tumor_nuclei_point: number;
      purity: { median: number; low: number; high: number };
      total_nuclei: { median: number; low: number; high: number };
      tumor_nuclei: { median: number; low: number; high: number };
      adequacy_probability: number;
    };
  }>;
}

function tilesFromFixture(f: Fixture): TileArrays {
  const tumor = new Float32Array(f.tiles.purity.length);
  for (let i = 0; i < tumor.length; i++) {
    tumor[i] = f.tiles.purity[i] * f.tiles.nuclei[i];
  }
  return {
    grid: f.grid,
    purity: Float32Array.from(f.tiles.purity),
    purity_sd: Float32Array.from(f.tiles.purity_sd),
    nuclei: Float32Array.from(f.tiles.nuclei),
    nuclei_sd: Float32Array.from(f.tiles.nuclei_sd),
    tumor_nuclei: tumor,
    tissue_fraction: Float32Array.from(f.tiles.tissue_fraction),
  };
}

describe("Python ↔ TypeScript metric parity (synthetic case)", () => {
  // Vitest's module resolver routes JSON imports through Node's CJS
  // require(); using require() directly keeps the fixture as a typed
  // Fixture without needing JSON schema decls.
  const fixture = require("./fixtures/metric_parity.json") as Fixture;
  const tiles = tilesFromFixture(fixture);

  for (const c of fixture.cases) {
    it(`case '${c.label}' agrees with Python`, () => {
      const poly: Point2D[] = c.polygon.map(([x, y]) => [x, y] as Point2D);
      const result = computeROIMetrics(poly, tiles, {
        thresholdsPurityMin: fixture.thresholds.purity_min,
        thresholdsTumorCellsMin: fixture.thresholds.tumor_cells_min,
        nSamples: 2000,
      });
      // Deterministic geometric quantities must match exactly.
      expect(result.n_tiles).toBe(c.expected.n_tiles);
      expect(result.tiles_with_data).toBe(c.expected.tiles_with_data);
      expect(result.area_thumbpx2).toBeCloseTo(c.expected.area_thumbpx2, 4);
      expect(result.area_mm2).toBeCloseTo(c.expected.area_mm2, 6);
      // Point estimates are deterministic functions of the raw tile grid;
      // tolerate float32 round-trip noise (~1e-5 relative).
      expect(result.purity_point).toBeCloseTo(c.expected.purity_point, 4);
      expect(result.total_nuclei_point).toBeCloseTo(c.expected.total_nuclei_point, 1);
      expect(result.tumor_nuclei_point).toBeCloseTo(c.expected.tumor_nuclei_point, 1);
      // Monte-Carlo percentiles use different PRNG streams; assert
      // sampling-noise-level agreement (≤3% relative on the median,
      // ≤8% on the wider 5/95 percentiles).
      const rel = (a: number, b: number) => Math.abs(a - b) / Math.max(Math.abs(b), 1e-9);
      expect(rel(result.purity.median, c.expected.purity.median)).toBeLessThan(0.03);
      expect(rel(result.total_nuclei.median, c.expected.total_nuclei.median)).toBeLessThan(0.03);
      expect(rel(result.tumor_nuclei.median, c.expected.tumor_nuclei.median)).toBeLessThan(0.03);
      expect(rel(result.purity.low, c.expected.purity.low)).toBeLessThan(0.08);
      expect(rel(result.purity.high, c.expected.purity.high)).toBeLessThan(0.08);
      // Adequacy probability is a Bernoulli ratio over n_samples; ≤5
      // percentage points of drift is well within the SE.
      expect(
        Math.abs(result.adequacy_probability - c.expected.adequacy_probability),
      ).toBeLessThan(0.05);
    });
  }
});
