"""Generate a server/client parity fixture for the ROI-metrics math.

Builds a deterministic synthetic case (6×4 tile grid, one tumor hotspot)
and three test polygons; computes the Python `compute_roi_metrics`
output for each polygon at K=2000 Monte-Carlo samples; serializes the
inputs and expected outputs to JSON. The TS-side parity test
(``tests/parity.spec.ts``) reads this fixture and asserts that its own
computeROIMetrics output matches Python within tight tolerances.

Run from the repo root::

    python frontend/tests/fixtures/dump_metric_parity.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from enso_purity.macrodissection.roi import (
    TileArrays,
    TileGrid,
    compute_roi_metrics,
)


def _build_synthetic_tiles() -> tuple[TileArrays, dict]:
    grid_nx, grid_ny = 6, 4
    grid = TileGrid(
        stride_x=20.0,
        stride_y=20.0,
        offset_x=0.0,
        offset_y=0.0,
        grid_nx=grid_nx,
        grid_ny=grid_ny,
        tile_area_mm2=0.012544,
    )
    shape = (grid_ny, grid_nx)
    purity = np.full(shape, 0.05, dtype=np.float32)
    nuclei = np.full(shape, 30.0, dtype=np.float32)
    # Left hotspot: high purity + high nuclei
    purity[:, : grid_nx // 2] = 0.6
    nuclei[:, : grid_nx // 2] = 200.0
    purity_sd = np.full(shape, 0.05, dtype=np.float32)
    nuclei_sd = np.full(shape, 5.0, dtype=np.float32)
    tissue = np.full(shape, 1.0, dtype=np.float32)
    tiles = TileArrays(
        grid=grid,
        purity=purity,
        purity_sd=purity_sd,
        nuclei=nuclei,
        nuclei_sd=nuclei_sd,
        tissue_fraction=tissue,
    )
    grid_meta = {
        "grid_nx": grid_nx,
        "grid_ny": grid_ny,
        "stride_x": 20.0,
        "stride_y": 20.0,
        "offset_x": 0.0,
        "offset_y": 0.0,
        "tile_area_mm2": 0.012544,
        "tile_size_um": 112.0,
        "mpp_thumb_x": 5.6,
        "mpp_thumb_y": 5.6,
    }
    return tiles, grid_meta


POLYGONS = {
    "hotspot": [(0.0, 0.0), (60.0, 0.0), (60.0, 80.0), (0.0, 80.0)],
    "background": [(60.0, 0.0), (120.0, 0.0), (120.0, 80.0), (60.0, 80.0)],
    "diagonal_clip": [(10.0, 5.0), (115.0, 12.0), (110.0, 70.0), (5.0, 60.0)],
}

THRESHOLDS = {"purity_min": 0.20, "tumor_cells_min": 1000}


def main() -> None:
    tiles, grid_meta = _build_synthetic_tiles()
    cases = []
    for label, poly in POLYGONS.items():
        metrics = compute_roi_metrics(
            poly,
            tiles,
            thresholds_purity_min=THRESHOLDS["purity_min"],
            thresholds_tumor_cells_min=THRESHOLDS["tumor_cells_min"],
            n_samples=2000,
        )
        cases.append(
            {
                "label": label,
                "polygon": poly,
                "expected": metrics.to_dict(),
            }
        )
    payload = {
        "_comment": "Generated by tests/fixtures/dump_metric_parity.py. Do not edit by hand.",
        "grid": grid_meta,
        "thresholds": THRESHOLDS,
        "tiles": {
            "purity": tiles.purity.reshape(-1).tolist(),
            "purity_sd": tiles.purity_sd.reshape(-1).tolist(),
            "nuclei": tiles.nuclei.reshape(-1).tolist(),
            "nuclei_sd": tiles.nuclei_sd.reshape(-1).tolist(),
            "tissue_fraction": tiles.tissue_fraction.reshape(-1).tolist(),
        },
        "cases": cases,
    }
    target = Path(__file__).resolve().parent / "metric_parity.json"
    with target.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=False)
        f.write("\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
