"""Refresh tests/fixtures/colormaps_python_lut.json from the Python LUTs.

Run from the repo root::

    python frontend/tests/fixtures/dump_python_lut.py

The output file is a JSON dict with stop-color RGB triples for each
palette; the TS-side colormap parity test (``tests/colormaps.spec.ts``)
reads it and verifies the LUT entries it interpolates match Python's
within one LUT step.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.colors as mcolors

from enso_purity.macrodissection.inverse_cmap import (
    PURITY_SPEC,
    CELLULARITY_SPEC,
)


def palette_stops(cmap: mcolors.Colormap, n: int = 11) -> list[list[int]]:
    rgba = cmap([i / (n - 1) for i in range(n)])
    return [[int(round(c[0] * 255)), int(round(c[1] * 255)), int(round(c[2] * 255))] for c in rgba]


def main() -> None:
    from enso_purity.macrodissection.inverse_cmap import _get_cmap

    out = {
        "_comment": "Generated by tests/fixtures/dump_python_lut.py. Do not edit by hand.",
        "purity_RdYlBu_r": palette_stops(_get_cmap(PURITY_SPEC.cmap_name), 11),
        "cellularity_purity_no_white": palette_stops(
            _get_cmap(CELLULARITY_SPEC.cmap_name), 7
        ),
    }
    target = Path(__file__).resolve().parent / "colormaps_python_lut.json"
    with target.open("w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
